## Worked example on a synthetic but realistic psychology Table 1.
##
## Demonstrates the full pipeline and the print/plot methods. The synthetic
## table is generated by `data-raw/make_synthetic_table1.R` and saved to
## `inst/extdata/synthetic_table1.rds`.

library(multiclosure)

dat <- readRDS(system.file("extdata", "synthetic_table1.rds",
                           package = "multiclosure"))

out <- multi_closure(
  N = dat$N, K = dat$K, M = dat$M, s = dat$s, R = dat$R,
  alpha = dat$alpha,
  max_candidates = 100L,
  stage4 = list(strategy = "bb_closest", max_combos = 500L,
                samples_per_combo = 1L),
  seed = 42L
)

print(out)
if (requireNamespace("ggplot2", quietly = TRUE)) {
  print(plot(out, what = "retention"))
  print(plot(out, what = "skew_bb"))
  if (out$candidates$n_returned > 0L)
    print(plot(out, what = "distances"))
}
